language: java
script: ant main
deploy:
  provider: releases
  api_key:
    secure: Ga3Qu0GaBwC1EXM+7KylTQzAC5EJL2+5U65pUMfy4qDprTVarWbMwh6LnLWtvXU9yyO/o6f4uMuMB5PlH/UuzTH/TR9N9mWt3afwSyCBlF2wYsO2JbiQV+5FdhJ8AwF4CM4yiHHE1MlVhzZTIAW1fQxeK80a8QrykO5eljdV6RAz0MxTQzlDnqhm2E3xPM/yNyF9vqxQk0qlUKwN2RKjp1DSEKRk3oOBaSCXd/qliRVOUsqkAgMkHSJ5BFPJUQJdirSfbBPgQ/C2mgX7dLTIwKdUXI5BwuhFNY7HBnQiKCsdgyIk5OqINGGbNPGXRe7JNengzP7K76Cpn9q3ECwCeoFo2ScrDmRfETC1yhkmQXj0JxUXA1H5PvUloK9uBdkMrgJF4lljTw4D6EhTxQSpVTxVt33upgb/a/QgOeeT3P6bFY86tPRklkL+EbkvT0t2pifTi8hfblZKYfKj4h0cKLqrlQlCFHz4jUtj7G4Ux0q9WsAR2aLbRQP2JpsJtT5z1HtpTnN4+zH9kPnYVtzuuhhc8ZGTiY86/0+OLKYEdaoHfxgeq0uSExpfOGsuEBhAiUSo+vVMcSdnaRpqHJfwtV2nvAcax5aViQIjjOlhawVFPYIDSdTI2IIoov5cU/zKqpjUtiD5TL1rnNa/Qw7rUFTaC15dXsMoe17X6rDci5Y=
  file: PULSimReleases/v0.9/PULSim.jar
  on:
    repo: Katsching/RailView
